sudo: false
cache: bundler
language: ruby
dist: trusty
rvm:
  - jruby-9.1.16.0
  - jruby-head
env:
  global:
    - JRUBY_OPTS='--debug -J-Xmx1000M' # get more accurate coverage data in JRuby
    - JAVA_OPTS='-Djava.security.egd=file:/dev/./urandom'
  matrix:
    - 'TASK=spec'
    - 'TASK=ascii_spec'
    - 'TASK=internal_investigation'
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
before_install:
  - gem update --system
  - gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - ruby .travis.rb
addons:
  code_climate:
    repo_token: a11b66bfbb1acdf220d5cb317b2e945a986fd85adebe29a76d411ad6d74ec31f
